USE SmartRecruiterDB;

INSERT INTO [dbo].[candidates] (
    [Name], 
    [Contact], 
    [Email], 
    [CV_FilePath], 
    [CV_FileName], 
    [Skills], 
    [Available_Date], 
    [GitHub_Link], 
    [LinkedIn], 
    [Degree], 
    [University],
    [Reason],
    [Experience], 
    [Role_Id]
) VALUES 
(
    'John Doe', 
    '123-456-7890', 
    'john.doe@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    1
),
(
    'Jane Smith', 
    '987-654-3210', 
    'jane.smith@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Alice Johnson', 
    '555-123-4567', 
    'alice.johnson@example.com', 
    'C:\\CVs\\alice_johnson.pdf', 
    'alice_johnson.pdf', 
    'Python, Django, Flask', 
    '2023-12-01', 
    'https://github.com/alicejohnson', 
    'https://linkedin.com/in/alicejohnson', 
    'B.Sc. Information Technology', 
    'Tech University', 
    'Passionate about coding', 
    '4', 
    3
),
(
    'Monica Brown', 
    '123-456-7890', 
    'monica@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '1', 
    0
),
(
    'Rachel Green', 
    '987-654-3210', 
    'rachel@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    0
),
(
    'Phoebe Buffay', 
    '123-456-7890', 
    'buffay@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    7
),
(
    'Rose Tyler', 
    '987-654-3210', 
    'jane.smith@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    7
),
(
    'Angel Fernando', 
    '123-456-7890', 
    'angel@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    1
),
(
    'Sajani Amanda', 
    '987-654-3210', 
    'sajani@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Sahan Mindika', 
    '555-123-4567', 
    'sahan@example.com', 
    'C:\\CVs\\alice_johnson.pdf', 
    'alice_johnson.pdf', 
    'Python, Django, Flask', 
    '2023-12-01', 
    'https://github.com/alicejohnson', 
    'https://linkedin.com/in/alicejohnson', 
    'B.Sc. Information Technology', 
    'Tech University', 
    'Passionate about coding', 
    '4', 
    3
),
(
    'Dinushika Abrew', 
    '123-456-7890', 
    'dinushika@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '1', 
    6
),
(
    'Rachel Keran', 
    '987-654-3210', 
    'rachel@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Ashan Wimalasooriya', 
    '123-456-7890', 
    'ashan@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    1
),
(
    'Sethma Nethmini', 
    '987-654-3210', 
    'sethma@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Pumudu Nadun', 
    '555-123-4567', 
    'pumudu@example.com', 
    'C:\\CVs\\alice_johnson.pdf', 
    'alice_johnson.pdf', 
    'Python, Django, Flask', 
    '2023-12-01', 
    'https://github.com/alicejohnson', 
    'https://linkedin.com/in/alicejohnson', 
    'B.Sc. Information Technology', 
    'Tech University', 
    'Passionate about coding', 
    '4', 
    3
),
(
    'Dinushika Abrew', 
    '123-456-7890', 
    'dinushika@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '1', 
    6
),
(
    'Michael Brown', 
    '078 5674386', 
    'michaelbrown@example.com', 
    'C:\\CVs\\michael_brown.pdf', 
    'michael_brown.pdf', 
    'JavaScript, React, Node.js', 
    '2023-09-20', 
    'https://github.com/michaelbrown', 
    'https://linkedin.com/in/michaelbrown', 
    'B.Sc. Software Engineering', 
    'Global University', 
    'Excited about full-stack development', 
    '2', 
    7
),
(
    'Emma Williams', 
    '078 5674388', 
    'emma.williams@example.com', 
    'C:\\CVs\\emma_williams.pdf', 
    'emma_williams.pdf', 
    'HTML, CSS, Angular', 
    '2023-12-05', 
    'https://github.com/emmawilliams', 
    'https://linkedin.com/in/emmawilliams', 
    'M.Sc. Computer Science', 
    'Tech Institute', 
    'Looking to enhance front-end skills', 
    '5', 
    0
),
(
    'Oliver Davis', 
    '078 5774386', 
    'oliver.davis@example.com', 
    'C:\\CVs\\oliver_davis.pdf', 
    'oliver_davis.pdf', 
    'Ruby, Rails, JavaScript', 
    '2023-11-25', 
    'https://github.com/oliverdavis', 
    'https://linkedin.com/in/oliverdavis', 
    'B.Sc. Information Technology', 
    'Example College', 
    'Aiming to specialize in back-end development', 
    '3', 
    0
),
(
    'Sophia Miller', 
    '078 5674686', 
    'sophia.miller@example.com', 
    'C:\\CVs\\sophia_miller.pdf', 
    'sophia_miller.pdf', 
    'C++, Python, Machine Learning', 
    '2024-01-10', 
    'https://github.com/sophiamiller', 
    'https://linkedin.com/in/sophiamiller', 
    'Ph.D. Data Science', 
    'Advanced Tech University', 
    'Keen on data-driven solutions', 
    '4', 
    0
);