USE SmartRecruiterDB;

INSERT INTO [dbo].[candidates] (
    [Name], 
    [Contact], 
    [Email], 
    [CV_FilePath], 
    [CV_FileName], 
    [Skills], 
    [Available_Date], 
    [GitHub_Link], 
    [LinkedIn], 
    [Degree], 
    [University],
    [Reason],
    [Experience], 
    [Role_Id]
) VALUES 
(
    'John Doe', 
    '123-456-7890', 
    'john.doe@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    1
),
(
    'Jane Smith', 
    '987-654-3210', 
    'jane.smith@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Alice Johnson', 
    '555-123-4567', 
    'alice.johnson@example.com', 
    'C:\\CVs\\alice_johnson.pdf', 
    'alice_johnson.pdf', 
    'Python, Django, Flask', 
    '2023-12-01', 
    'https://github.com/alicejohnson', 
    'https://linkedin.com/in/alicejohnson', 
    'B.Sc. Information Technology', 
    'Tech University', 
    'Passionate about coding', 
    '4', 
    3
),
(
    'Monica Brown', 
    '123-456-7890', 
    'monica@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '1', 
    0
),
(
    'Rachel Green', 
    '987-654-3210', 
    'rachel@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    0
),
(
    'Phoebe Buffay', 
    '123-456-7890', 
    'buffay@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    7
),
(
    'Rose Tyler', 
    '987-654-3210', 
    'jane.smith@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    7
),
(
    'Angel Fernando', 
    '123-456-7890', 
    'angel@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    1
),
(
    'Sajani Amanda', 
    '987-654-3210', 
    'sajani@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Sahan Mindika', 
    '555-123-4567', 
    'sahan@example.com', 
    'C:\\CVs\\alice_johnson.pdf', 
    'alice_johnson.pdf', 
    'Python, Django, Flask', 
    '2023-12-01', 
    'https://github.com/alicejohnson', 
    'https://linkedin.com/in/alicejohnson', 
    'B.Sc. Information Technology', 
    'Tech University', 
    'Passionate about coding', 
    '4', 
    3
),
(
    'Dinushika Abrew', 
    '123-456-7890', 
    'dinushika@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '1', 
    6
),
(
    'Rachel Keran', 
    '987-654-3210', 
    'rachel@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Ashan Wimalasooriya', 
    '123-456-7890', 
    'ashan@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '5', 
    1
),
(
    'Sethma Nethmini', 
    '987-654-3210', 
    'sethma@example.com', 
    'C:\\CVs\\jane_smith.pdf', 
    'jane_smith.pdf', 
    'Java, Spring, Hibernate', 
    '2023-11-15', 
    'https://github.com/janesmith', 
    'https://linkedin.com/in/janesmith', 
    'M.Sc. Software Engineering', 
    'Example University', 
    'Seeking a challenging role', 
    '3', 
    2
),
(
    'Pumudu Nadun', 
    '555-123-4567', 
    'pumudu@example.com', 
    'C:\\CVs\\alice_johnson.pdf', 
    'alice_johnson.pdf', 
    'Python, Django, Flask', 
    '2023-12-01', 
    'https://github.com/alicejohnson', 
    'https://linkedin.com/in/alicejohnson', 
    'B.Sc. Information Technology', 
    'Tech University', 
    'Passionate about coding', 
    '4', 
    3
),
(
    'Dinushika Abrew', 
    '123-456-7890', 
    'dinushika@example.com', 
    'C:\\CVs\\john_doe.pdf', 
    'john_doe.pdf', 
    'C#, SQL, ASP.NET', 
    '2023-10-01', 
    'https://github.com/johndoe', 
    'https://linkedin.com/in/johndoe', 
    'B.Sc. Computer Science', 
    'University of Example', 
    'Looking for new opportunities', 
    '1', 
    6
);